server:
  port: 8999
spring:
  application:
    name: easyDbDemo
mybatis:
  mapper-locations: classpath*:mapper/*Dao.xml
  type-aliases-package: io.github.jinlongliao.easy.db.demo.mybatis.entity

easy:
  db:
    datasource:
      default:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
        type: org.apache.tomcat.jdbc.pool.DataSource
        username: silu
        password: 59421
        driver-class-name: com.mysql.cj.jdbc.Driver
      db1:
        url: jdbc:mysql://localhost:3306/CMDB?serverTimezone=UTC
        type: org.apache.commons.dbcp2.BasicDataSource
        username: silu
        password: 59421
        driver-class-name: com.mysql.cj.jdbc.Driver
      db2:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
        type: com.alibaba.druid.pool.DruidDataSource
        username: silu
        password: 59421
        driver-class-name: com.mysql.cj.jdbc.Driver
        extProps:
          filters: stat,wall,log4j2,config
          max-active: 100
          initial-size: 1
          max-wait: 60000
          min-idle: 1
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: select 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-open-prepared-statements: 50
          max-pool-prepared-statement-per-connection-size: 20
